sas_logo: bitmap
60x60
<
   ff ff ff ff ff ff ff 0f ff ff ff ff
   ff ff ff 0f ff ff ff ff ff ff ff 0f
   ff ff ff ff ff ff ff 0f ff ff ff ff
   ff ff ff 0f ff ff ff ff ff ff ff 0f
   ff ff ff ff ff ff ff 0f ff ff ff ff
   ff ff ff 0f ff ff ff ff ff ff ff 0f
   ff ff ff ff ff ff ff 0f ff ff ff ff
   ff ff ff 0f ff ff ff ff ff ff ff 0f
   ff ff ff ff ff ff ff 0f ff ff ff ff
   ff ff ff 0f ff ff ff ff ff ff ff 0f
   ff ff ff ff ff ff ff 0f ff ff ff ff
   ff ff ff 0f ff ff ff ff ff ff ff 0f
   ff ff ff ff ff ff ff 0f ff ff ff ff
   ff ff ff 0f ff ff ff ff ff ff ff 0f
   ff ff ff ff ff ff ff 0f ff ff ff ff
   ff ff ff 0f ff ff ff ff ff ff ff 0f
   ff ff ff ff ff ff ff 0f ff ff ff ff
   ff ff ff 0f ff ff ff ff ff ff ff 0f
   ff ff ff ff ff ff ff 0f ff ff f0 ff
   c1 7f f8 0f ff 3f 00 ff c0 1f 80 0f
   ff 3f f8 7f c0 0f fc 0f ff 1f fc 3f
   c0 0f fe 0f ff 1f fc 3f c0 07 fe 0f
   ff 1f f8 1f c0 07 fe 0f ff 1f f8 1f
   e0 07 fe 0f ff 1f f8 27 e0 07 fc 0f
   ff 1f f8 37 e0 0f fc 0f ff 1f f0 39
   e0 0f fc 0f ff 3f f0 31 e0 0f fc 0f
   ff 3f f0 00 f0 0f f8 0f ff 3f 70 1c
   f0 1f f8 0f ff 3f 30 1e f0 1f f8 0f
   ff 3f 80 1f e0 0f fc 0f 3f 3e c8 1f
   80 0f fc 0f 7f 0e c8 1f d8 07 fe 0f
   ff 01 f7 1f 7c 80 ff 0f ff ff ff ff
   ff ff ff 0f ff ff ff ff ff ff ff 0f
   ff ff ff ff ff ff ff 0f ff ff ff ff
   ff ff ff 0f ff ff ff ff ff ff ff 0f
   ff ff ff ff ff ff ff 0f ff ff ff ff
   ff ff ff 0f ff ff ff ff ff ff ff 0f
   ff ff ff ff ff ff ff 0f ff ff ff ff
   ff ff ff 0f ff ff ff ff ff ff ff 0f
   ff ff ff ff ff ff ff 0f ff ff ff ff
   ff ff ff 0f ff ff ff ff ff ff ff 0f
>
end
