#!/bin/sh

export DAVE_FETCH_THREADS=0
export DAVE_FORK_PROTECTION=1

echo "DAVE_FETCH_THREADS = " $DAVE_FETCH_THREADS
echo "DAVE_FORK_PROTECTION = " $DAVE_FORK_PROTECTION

if [[ $4 == *"_1" ]]; then
   echo "Process name ends with _1. Going right ahead."
   :;
elif [[ $4 == *"_2" ]]; then
   echo "Process name ends with _2. Waiting ten seconds before start."
   for i in {10..1}; do
      echo $i
      sleep 1;
   done
else
   echo "Process name doesn't end with _1 or _2. Exiting.";
fi

echo "Executing $CARMSYS/etc/scripts/reportworkerJmp $@"
exec $CARMUSR/bin/manpower/bids/startReportServer $@
