#!/bin/sh

# added for SKS-170 # export DAVE_FETCH_THREADS=1
export DAVE_FETCH_THREADS=0 
export DAVE_FORK_PROTECTION=1

echo "DAVE_FETCH_THREADS = " $DAVE_FETCH_THREADS
echo "DAVE_FORK_PROTECTION = " $DAVE_FORK_PROTECTION

if [[ $3 == *"_1" ]]; then
   echo "Process name ends with _1. Going right ahead."
   :;
elif [[ $3 == *"_2" ]]; then
   echo "Process name ends with _2. Waiting ten seconds before start."
   for i in {10..1}; do
      echo $i
      sleep 1;
   done
else
   echo "Process name doesn't end with _1 or _2. Exiting.";
fi

# Added for SKS-170 to increase log level
# if [[ $3 == "SAS_RS_WORKER_SCHEDULED_1" || $3 == "SAS_RS_WORKER_SCHEDULED_2" ]]; then
   # echo "set environment CFLL=2 to increase log level for $3"
   # export CFLL=2
# fi
# END of added for SKS-170

echo "Executing $CARMSYS/etc/scripts/reportworkerStudio $@"
exec $CARMSYS/etc/scripts/reportworkerStudio $2 $3
