INSERT INTO CP_SAS.NOTIFICATIONMESSAGEPARAMETERS (NOTIFICATIONID, PARAMETERINDEX, PARAMETERVALUE) VALUES (507, 0, '5:00');
INSERT INTO CP_SAS.NOTIFICATIONMESSAGEPARAMETERS (NOTIFICATIONID, PARAMETERINDEX, PARAMETERVALUE) VALUES (166, 0, '15');
INSERT INTO CP_SAS.NOTIFICATIONMESSAGEPARAMETERS (NOTIFICATIONID, PARAMETERINDEX, PARAMETERVALUE) VALUES (166, 1, '12');
