INSERT INTO CP_SAS.USERDIRECTORY (USERID, PASSWORD, FIRSTNAME, LASTNAME) VALUES ('admin', 'admin', 'admin', 'admin');
INSERT INTO CP_SAS.USERDIRECTORY (USERID, PASSWORD, FIRSTNAME, LASTNAME) VALUES ('testuser', 'null', 'Tester', 'Testuser');
