INSERT INTO CP_SAS.QRTZ_LOCKS (LOCK_NAME) VALUES ('CALENDAR_ACCESS');
INSERT INTO CP_SAS.QRTZ_LOCKS (LOCK_NAME) VALUES ('JOB_ACCESS');
INSERT INTO CP_SAS.QRTZ_LOCKS (LOCK_NAME) VALUES ('MISFIRE_ACCESS');
INSERT INTO CP_SAS.QRTZ_LOCKS (LOCK_NAME) VALUES ('STATE_ACCESS');
INSERT INTO CP_SAS.QRTZ_LOCKS (LOCK_NAME) VALUES ('TRIGGER_ACCESS');
