INSERT INTO CP_SAS.SEARCHPROPERTIES (SEARCHPROPERTYID, TRIPSEARCHID, SORTORDER, SEARCHPROPERTYTYPE) VALUES (298, 119, 0, 'check_in');
INSERT INTO CP_SAS.SEARCHPROPERTIES (SEARCHPROPERTYID, TRIPSEARCHID, SORTORDER, SEARCHPROPERTYTYPE) VALUES (381, 161, 0, 'check_in');
