INSERT INTO CP_SAS.USERS (USERID, LOGINID, PASSWORD, FIRSTNAME, LASTNAME, MESSAGESLASTREAD, INACTIVE) VALUES ('admin', 'admin', 'admin', 'Admin', 'User', null, null);
INSERT INTO CP_SAS.USERS (USERID, LOGINID, PASSWORD, FIRSTNAME, LASTNAME, MESSAGESLASTREAD, INACTIVE) VALUES ('testCrew', 'testCrew', null, 'Tester', 'Tester', null, null);
INSERT INTO CP_SAS.USERS (USERID, LOGINID, PASSWORD, FIRSTNAME, LASTNAME, MESSAGESLASTREAD, INACTIVE) VALUES ('testCrew1', 'testCrew1', null, 'Tester1', 'Tester1', null, null);
