INSERT INTO CP_SAS.SEARCHPROPERTYENTRIES (SEARCHPROPERTYENTRYID, SEARCHPROPERTYID, ENTRYKEY, ENTRYVALUE) VALUES (719, 298, 'end_time', '07:00');
INSERT INTO CP_SAS.SEARCHPROPERTYENTRIES (SEARCHPROPERTYENTRYID, SEARCHPROPERTYID, ENTRYKEY, ENTRYVALUE) VALUES (720, 298, 'start_time', '05:30');
INSERT INTO CP_SAS.SEARCHPROPERTYENTRIES (SEARCHPROPERTYENTRYID, SEARCHPROPERTYID, ENTRYKEY, ENTRYVALUE) VALUES (901, 381, 'end_time', '10:00');
INSERT INTO CP_SAS.SEARCHPROPERTYENTRIES (SEARCHPROPERTYENTRYID, SEARCHPROPERTYID, ENTRYKEY, ENTRYVALUE) VALUES (902, 381, 'start_time', '04:30');
