INSERT INTO CP_SAS.USERDIRECTORY (USERID, PASSWORD, FIRSTNAME, LASTNAME) VALUES ('admin', 'admin', 'admin', 'admin');
INSERT INTO CP_SAS.USERDIRECTORY (USERID, PASSWORD, FIRSTNAME, LASTNAME) VALUES ('testCrew', 'null', 'Tester', 'testCrew');
INSERT INTO CP_SAS.USERDIRECTORY (USERID, PASSWORD, FIRSTNAME, LASTNAME) VALUES ('testCrew1', 'null', 'Tester', 'testCrew');
