INSERT INTO CP_SAS.USERS (USERID, LOGINID, PASSWORD, FIRSTNAME, LASTNAME, MESSAGESLASTREAD, INACTIVE) VALUES ('admin', 'admin', 'admin', 'Admin', 'User', null, null);
INSERT INTO CP_SAS.USERS (USERID, LOGINID, PASSWORD, FIRSTNAME, LASTNAME, MESSAGESLASTREAD, INACTIVE) VALUES ('testuser', 'testuser', null, 'Tester', 'Tester', null, null);
