INSERT INTO CP_SAS.TRIPSEARCHES (TRIPSEARCHID, NAME, USERID) VALUES (97, 'Filter 97', 'testCrew');
INSERT INTO CP_SAS.TRIPSEARCHES (TRIPSEARCHID, NAME, USERID) VALUES (119, 'Filter 119', 'testCrew');
INSERT INTO CP_SAS.TRIPSEARCHES (TRIPSEARCHID, NAME, USERID) VALUES (127, 'Filter 127', 'testCrew');
INSERT INTO CP_SAS.TRIPSEARCHES (TRIPSEARCHID, NAME, USERID) VALUES (138, 'Filter 138', 'testCrew');
INSERT INTO CP_SAS.TRIPSEARCHES (TRIPSEARCHID, NAME, USERID) VALUES (161, 'Filter 161', 'testCrew');
