= Run SAS project
:toc:

== 'dev' structure
it includes required resources for the project to run it with docker or docker-compose.

. *docker*: to run app with docker locally or on CI
. *openstack*: to run app with openstack instance on CI
. *xmlrpc-mock-server*: implementation project of xmlrpc mock server to run app without backend servers.

== Prepare environment
To run mvn(w) commands without '-s' flag add '/bids_user/dev/settings/.m2/settings.xml' to your local maven repo.

Working directory: 'bids_user'
[source, shell]
----
cd bids_user
----

== Windows OS

=== Build the project
.windows shell
[source, cmd]
----
# prepare project war files
mvnw clean install

# prepare xmlrpc mock server jar file
mvnw clean install -f .\dev\xmlrpc-mock-server
----

=== Run app with docker-compose
There are two options to run app:

. Mocked backend completely
. Manpower backend and other mocked backend

==== Mocked backend completely
There are 3 mock servers to generate response from xmlrpc servers:

. xmlrpc-vacation - mock for 'vacation' tab
. xmlrpc-manpower - mock for 'fda' tab
. xmlrpc - mock for 'interbid' tab generates responses for FS-requests and etc.

.windows shell
[source, cmd]
----
# To start app
mvnw -f .\dev\docker\ -P up

# To shutdown app and remove containers
mvnw -f .\dev\docker\ -P down
----

==== Manpower backend and other mocked backend
There is a manpower configuration that uses to connect to manpower test servers.
So all requests from 'vacation' and 'fda' tab will be delivered to those servers.
FS-requests is still mocked by xmlrpc mock server.

.windows shell
[source, cmd]
----
# To start app
mvnw -f .\dev\docker\ -P manpower-up

# To shutdown app and remove containers
mvnw -f .\dev\docker\ -P down
----

== Unix OS or shell

=== Build the project
.unix shell
[source, bash]
----
# prepare project war files
mvnw clean install

# prepare xmlrpc mock server jar file
mvnw clean install -f ./dev/xmlrpc-mock-server
----

=== Run app with docker-compose
There are two options to run app:

. Mocked backend completely
. Manpower backend and other mocked backend

==== Mocked backend completely

.unix shell
[source, bash]
----
# To start app
mvnw -f ./dev/docker/ -P up

# To shutdown app and remove containers
mvnw -f ./dev/docker/ -P down
----

==== Manpower backend and other mocked backend

.unix shell
[source, bash]
----
# To start app
mvnw -f ./dev/docker/ -P manpower-up

# To shutdown app and remove containers
mvnw -f ./dev/docker/ -P down
----

== Login on site
http://localhost:8080/sas/

----
User name: admin
Password: <any>
----

== Gitlab integration
There are the next key jobs:

.Job list
|===
|Name|Description
|build oracle image
|create oracle db image and upload it to artifactory

|prepare docker images
|generate all project images, upload them to artifactory.  It's required for openstack-based app running and applicable for local testings as well

|Openstack manpower docker-compose installation
|run app with openstack and manpower backend configuration

|Openstack mock docker-compose installation
|run app with openstack and mocked xmlrpc backend

|sonar analysis
|gather different statistic, provide control code quality. Statistic is available here: http://sonar.got.jeppesensystems.com/dashboard?id=com.jeppesen.carmen.customization.sas%3ASAS.crewportal

|===

== Images on artifactory
All images of the poroject: https://binaryrepo.service.cloud.jeppesensystems.com/artifactory/webapp/#/artifacts/browse/tree/General/docker-dev/crew-buddies/ib6-sas
