#!/bin/env python


"""
SASCMS-6487 Add attribute "TEMPORARY" to table vacation_status_set
"""

import adhoc.fixrunner as fixrunner


__version__ = '1'



@fixrunner.once
@fixrunner.run
def fixit(dc, *a, **k):
 
    ops = []

    if len(fixrunner.dbsearch(dc, 'vacation_status_set', "id='TEMPORARY'")) == 0:
        ops.append(fixrunner.createOp('vacation_status_set', 'N', {'id': 'TEMPORARY',
                                                                   'si': 'Temporary vacation, for instance the vacation generated by the dryrun assigner will set the status as temporary'}))
    else:
        print 'vacation_status_set entry "TEMPORARY" already exist'

    return ops


fixit.program = 'sascms-6487.py (%s)' % __version__

if __name__ == '__main__':
    fixit()
