name: Conflict Detection
on:
 pull_request_target:
   types: [opened, synchronize]
jobs:
 check-conflict:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
       with:
         ref: main
     - name: Checkout target branch
       run: git checkout AutomatedBranchingWF
     - name: Merge feature branch into target branch
       run: |
         git merge --no-commit --no-ff ${{ github.event.pull_request.head.ref }}
         if git diff --exit-code; then
           echo "No conflicts detected"
         else
           echo "Conflicts detected"
           # You can perform additional actions here, such as failing the workflow or notifying stakeholders
           exit 1
         fi
