name: Conflict Resolution
on:
 pull_request:
   types: [opened, synchronize]
jobs:
 detect-conflict:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - name: Detect conflicts
       id: conflict
       run: |
         if git merge --no-commit --no-ff origin/${{ github.event.pull_request.head.ref }}; then
           echo "No conflicts detected."
           echo "::set-output name=conflict::false"
         else
           echo "Conflicts detected."
           echo "::set-output name=conflict::true"
         fi
