name: Conflict Resolution
on:
 pull_request_target:
   types: [opened, synchronize]
jobs:
 resolve-conflict:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
       with:
        ref: main
         # ref: ${{ github.event.pull_request.head.sha }} # Checkout the head branch of the pull request

     - name: Pull Latest Change
       run: git pull origin main
       
     - name: debug
       run: echo "${{ github.event.pull_request.base.ref }}"
       
     - name: Checkout Base Branch
       run: git checkout origin/${{ github.event.pull_request.base.ref }}
       
     - name: Detect conflicts
       id: detect-conflicts
       run: |
          if git merge --no-commit --no-ff origin/${{ github.event.pull_request.head.ref }}; then
            echo "::set-output name=conflict::false"
          else
            echo "::set-output name=conflict::true"
          fi
