name: Conflict Resolution
on:
 pull_request:
   types: [opened, synchronize]
jobs:
 detect-conflict:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - name: Detect conflicts
       id: conflict
       run: |
         git fetch origin ${{ github.head_ref }}
         git checkout ${{ github.head_ref }}
         git merge origin/${{ github.base_ref }} --no-commit --no-ff
         if [ $? -eq 0 ]; then
           echo "No conflicts detected."
           echo "::set-output name=conflict::false"
         else
           echo "Conflicts detected."
           echo "::set-output name=conflict::true"
         fi
